homeurl=https://automationexercise.com/
login_url=https://automationexercise.com/login
product_pageUrl=https://automationexercise.com/products
checkoutPage_url=https://automationexercise.com/checkout
cartPage_url=https://automationexercise.com/view_cart
browser=chrome
implicitWait=5
explicitWait=10
username=gupta568@gmail.com
password=demo123
cardHolderName=Raj
CardNumber=125963789415
CVC=589
expirationMonth=06
expirationYear=2028


